language: python
python:
- '3.6'
cache: pip
env:
  global:
    - secure: Duu5/XtdMQym6uZ+EbWv9Y04e+7pIZjVYrVKJMwN6prj+cMcQtfEOSntFFfqE/g9bcnhb+p9htAVxWXO9iU0EauD9W45X4F2gPY4AiiNE8f73VhnIYZELHqOE+h3uQBZHdu/VqRn6Ao1ovh8hL9G6PtgjJ674IouMfZ823MCxjbf1s/Af52BTqTx5i81O3xX0LknCJmSwp0Muwnua1+k/RHIIoRWqV06nOVn1WVatgDz1cP7a751cCKfTOeMFoYepVaKlh+T3+2hgx4zj23S5Z2w7wv9FSGyzk0pvXq2dbHcL1TZYswixWFetw1xSx8T9wyMKxoHWzgSrhqJ/VxPTv/Ox86YQCWHoMfBnURUSAbUBSCboWi9ssTNt7oRDjt6QCmxuL1IfUsL/4wRWwVu5cJJvvtPkih+s41H3ejPpTeLxyi0JHPoRa5hoiGBjVrXj/4pD5HeruMEl+M5TPkJ0gLSx762RqzWMmYUlJKcaZZJ4wVllftT8U5Yt8tR/t3DHAa2GSvKkMSN3oz1LpPeQrzTacm+nAOo2C0grSPrdnxmo0l3aCYGNyUhtStxV467IcyMVtR/XH327+fOECJo/mSFCo0X0PeaOD4aex8rBS3RnQhOPxFPv8JkLE0DbMzXNDbYJeoYaUtXaJuJ4RKs0BugpeeirXADJxvm0X3doMU=
    - secure: xGU7E+6E9jzjUmPaT3JPcr2EYfX0XaqsKekFuRcDvs904ky8LsDN2xpa9FvlGn0G3qgv5lDhqjyV6b8C8X4Dy3HNJrsMaE0AYVm5Sz89t+CBBSoDUvqBzOYRS8e3+oXILR2DjMxp+TPl+NmYM4LmrjHWcSPAEFoe2B3ofqW3DBM5ecxoqGA6eB4xz9pGtU7YQTWAe9OFBwcYBmQNmhRQHYDtdHvsVtaRuLeOT3qif6qhS3cCm1SVXkPj3j+JFrhJE/el7RT9kHhMF73FhFjPAQ7WTJxRc6s70SEQBT7lMlOA2L65g/aS63GOAl0qMwjSDf4n+SaynF4E6e9VbVZrM57G/XreEIDaOrfodwKtowwHFon3TSNinTXPJH/tp6+TudgYpjjzK6MqieAcd8vWIjEhpFVUEe2tCNf1K/69SZj21PTxZastQ0QTifT+8UVdMY6pDFy7KRr0gfDwIn2pjGvPagXMjBqwd7+eku1+32Hk2wD8GAir/dE4oAsWOEeWvnQDolH7pfdcneTxSNbDjjp1UKQGQ0d5DiXdcEEGnY3kzgA9jEEYT8oK4KaEzxpUtZ82ZCeF3l0A6YY1Ock/IJ0zjgJRxA4lD6y1pco9uiEXGZkxjmOBtBjc6KQpKvV/hZpPmYfZtwnAHeahzJZy3vDZWJlDUfRV8pxEvbieRd8=
install:
  - pip install -r requirements.txt
  - pip install awscli
script:
  - make html
deploy:
  on:
    branch: master
  provider: s3
  access_key_id:
    secure: nk8xuMqmQnULItO45XDyPkZ7+0hG6Dc6s0SOC5el6JRAmnzhvn3gM7V6OJl2WYosjkwBRskLz3ffxkT3vMKS/TymAHs+G0DUKtxgUzZWaZLfqWCr9KhtF8Y9dWBIyH9wx8xLeR+tQ1jnjEOVq65OuNvxO5JtM3UKXsUiw7TNJwR/TDb84h35k+ncXxKtPESwiQghchO7BRF5MVlLEankMlEYBJKveU7W8ho6Xa/bhJC1KDMbiquRG2NpmxMGxXFknELUf2gviT6GkEnsRTNCp6mzwG79uYO8S//RioiysuvkRZqQiKAe5fy3xPszFes/xHCYLQIQ7O7t9mrDAFy7qJjz/d57zs/5jVSmAIp2UcdJWaVtBHOJw8Z9DR2dGCaqvr9SliLmYJFv1KJs5AOJ7vN9jLQAr3XUXmeB6u7Hlwh+H/MHr0/cuU0NFhN+68HKVyKXL6gN0vxay8+7Hnem1ySRVBDm0A6Wvrwq60zw/2ZZPPVcr4d65fMdZnUxkqXTGy9A6raVXE412bZojKLOAGfWoAgVQllzMy2bsHuKQGkhFRKHBlQrr/+nFXARG6SxPik29ozcM3VOgG2BRbXqk6YP58eocOUiKjIhzqYBpaJDI3o6mBAyfR6817rRjfZcXdyGnn2A+Y4eOK7wNlCCumRHrm2M6qJ7SME7ktMOl4g=
  secret_access_key:
    secure: T9y6WCrt5PPGLC8EHzKhTqhMXilFsNyONI1kDW3pLwDxbRlLmysr1PmP5RY6fLRH2c3stz/aFMQcmeOqrOYGRDHLEwCAQeXlHUW7ehQdIISSE2WXrpFUxSCi6dvc7dUbNTDniGpPZNtRBcYnUESKrNcw34fI0lo4316DnSE+V0FAuvAeaHegexxkZchUW3Fv6+LNuJZ11L+KX03jg2eSnnclb1984jmoDKRnosjslN4pcaN/fCb20xEHmisX7d7vcvcUT2oLLtGN6OXjg59v1kiDQfk0kCC4rUZnEvO540oo5THRpiiG8v3B9G3Ud0575mzzQja43MQIy+6jjLitTYBPZazLH+j/FbULJAqgTNqNufYB2KmHCTQ2vqYwZsJ7ydTQCf4faW7bOz+8AMFbwW3Dt7rRtrazga9vKpdCXkXYALUlx4ZMKiGDVN+y2gVpFdLls4uBxMO13KL7SCPTDN8E1Gbksqj8VJzTVt2HwsvFW1Nxpw9sEhJFLIwNc93jtHcRLpQvRu8QKkghCkqsOECCRkTIZDM+FFjS3ozja63iox4oBLW0k15nxkRfFqziBtBd/9z/9tOZ+BQRWAIZrlMIpM/5naOzso1xijR4/z9MnFMmYgY6m2Sl1L9R4ubFsPbE//X+QOjX0sY3ubw4/syadnIG3TA7drz9BCSscwM=
  bucket: 20180313-docs
  region: eu-central-1
  skip_cleanup: true
  local_dir: build/html
  # The cache_control property sets the length of time that files should be cached in the Cloudfront Edge location _and_ the user browser.
  cache_control: max-age=21600
after_deploy:
  # Bust the cloudfront edge cache, invalidate every object in the distribution
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
