language: python
python:
- '3.6'
cache:
  - pip
  - npm
  - directories:
    - .cache
    - /home/travis/.nvm
env:
  global:
    # Upload credentials
    - secure: qA8IivKhQQ4oebUhbj4+jOipwWS8wOF6n7isSp1enlUXybRS1UgahSZ62nrlv1e/jGYw2oh+tdF3R93qa9ej2W+GyqJ2V/GtbgMUR/hSgLkcSN3ay4MgDSmWYRJJFBTpglv7Id3y/4y5oTo6SBjZr6mZ2ylRkOu+FxHlgDHtgk20ophi5hhzt7bTVyFGuZ9jtzPYhbVBrXHdrEKknQfnlOpkhnIjZrBiaZDq1OpliRJT/TRF5wdN0k2NvVLVZsYcaXEZnxOCtz0f4zW4HdgAJek78BSrSQhAxDK54QF3DauZodLKUfVIb2CQr/pXME33OByudA7Ryrroo+r2W8HSsLu69DiSe2U+MHmpf8W4JPhgDW6IwTgJDV8bVwxIrYNdnNax+MiVpXhLoVQD5bkfXMwv2EG5i2+774YYEnrLJxxuiq4YGr0qw+Y0/g8iM8sauVab3FCZjD+i0/YdmivF3lJa0U3KFSKWznqIFbZxKzKrvm8lNwCLgvGbKHG1OOK3KDCekP8Gdl4sOPLG82TUZmo/Gi/2IoQ8s4F9qLvyQ4ANAsSYeDreWv5nysC6nx9Fxk/3gWbOVn9kL7ppJpYYi289IyqNEviMbvw814aNCfooPdquYP3I+rGoIIgRAkwnAM7uq2Qa07BYfzuLNmZi/L6ebIO7HT2s06LiCRvlHD0=
    - secure: ZFLl/A0aJE1bfHcq+DXRwm2t9o29XQsTJWOzFaMpc4rS8rXwCcXhOKN5iAT4o6ZXvxHQRUA+yFr7Xa3L5T1J/lLb3m29Hjrn2xUlyNo8MpT2BDi3dtRZ+mS8abbGyuBEIAq/B67E5G5WZFSUhebnlhvR+304sr8JUcZNvmnI5D8qLxnn7ai5gjb946Q9CIBKyq0aqU2uKK3qrC23/EvmyHP+HgU948URc1/5f5rF08U8j/WnqPXG99+r1on9sqkkIUaD6n2mhEjktk9hREMJNOD/OTB6+rIE2sCeyOHxhEUhHbNh2lw8ZsSeB8XLUOBUXKRuJ8/kks0E3CU6Sk/Dnpbc/q/6hXDA4T+tPp049kt+a5GRwQEBhm3O0UpnLTS77BG6hIZncSyzHnsUSrdNJGxxzY5bG+7E9KbHlpbM1CLvC9qvDko5xyK/dBRmZe6T7kMBnXI7KbXEt5m9LrDMSZ3R0H9bvEFYMfY+6Ql7QXhGNV0AcnnVyZ+AmZP46/Ps6w9gj29HrEBKIlt1Mu+NjXzCIR8WQXl/2xH7nwzRsyAT1bZfaXEg7e3v0H5hwnuAf1wG/giYdn/0167nQwArZ7VlhT0zCWWAj7+qnvX3VEMKgTSw8Hr6/Zsye7AXdkXewalFE414EM4L9HFHiLcD214DpVCsYO8MgPWQoRO5dik=
    # CloudFront credentials
    - secure: sPi7WBC1e9+GTp9OpqD0ICllPDfErJu8/VLJyoaqNcn0lZrrkXbiUmn6i9+Ae7kyeTjOKXrtTgHOGAU9tLiD08j2V7STtui1TJKSIjpOJER4ir33Zyh1eQ00JjVkb/4Vsg5Aq1LuP1F0VDZz0ASYFvCSy2m+icXtawkMLa0E9/8Ci9L7hhyR9M7Minv+VEimM6I1rg2ZGmwGvwAPPlL1smkhIY2aebRvKc0C3Wax5lBKMegrZjQjqUvGh2CeI0B02F5HDJ+LMXuMiDMYDtvL+gHoEuYUu7sDv1eOBiI+E5Dozg4YjnswW+H1eQQXkO6hQRVXvpjKewmYDmAsrY3Ow+INFlDWAoMb4aZfe7ubLZHwpErK35CItMMFKS6MXN58bQPDZZWkxA7EnRdkXD0K/XWniXN/vG8yjTwFDp7Z9dUUKIx0KKGWOOZJ6ewLB7VrNEPyiQiQ3hgpCt6Q7/XcA5Bq6GVthEZbYB/BEvN5IzJwXk+KmrnNzByYTTgapH90YXDuWY69+fwWukg1PSfOnvGUyNurSZmgDpSeWSDkkTJLVZqfFBz1aqU0t+arY4VkVPlfn/IcycPgUY5knjaBQmgMowm/KyXDwdm2J/5byY6Fe4FI/G5Ht7bhvhbZE8/QZRMHzWDU3047Z0GOCQT3SV94qpnASm+s1I8/11ONS6s=
    - secure: AoJqE/GBwW7Ci8ukf6h6QEtYFvarlph86BDtk42wQKU47i5xG51/MwX7Rx1ggcFSsL4JquXLvrQgqzfMKX9OywHIHZgwo0wAxUQNEjpBSbl7LeY9/V1Qfn5gPEohuwoeclCMIYqEUtEewR9EIp2Qr5xZ8oT41/+6qZFMciVaebGAOt8RUcvSvjDrUjPYaYhAayXuj3xC91ENd2YjXHR0DkA71u7mGtNK7PkbpMgxI3POLW1Lr2d+0WnqYVMsKjZJLUXU5SzsT2i2YEPf8G7VAGov+UWZWTJ784C+QQxzf/tMCVhPhDt6JSovr1a4Uo8mG7ZNDRMFYX2LK1JhELu+1HVKlj+P9ZqeKW/6uQbp90fjoTh370008Jk2MdpwBXVdX0YwNIJqri3H00ssPhdje9RpcezbJNWgZ02fTk01guIrDFM/08+61E5Nm4asF7WGgZ5lUCPt6kYCxkUpJ93Tb3VdfPVThFJavULqljLS/imwtXb/kOaatsHHJfsiBElEjYZN4MWQ45Kg/s31vI3481NNZ8FTjGX2bYzCwY0caBc6N38WNERuaTSzFihV+pbFhi0+khvZMedrj9/Nj+fto40iSDUriQ/C8SQFHZgGJ8ypcGxGiLoUi2spGTiOJMvP868xanwoBm8/LeNibE8SYaorsoQ751eXs6OthaE0sBo=
    - AWS_BUCKET="20180313-docs"
    - AWS_REGION="eu-central-1"
install:
  - nvm install $(cat .nvmrc)
  - travis_retry npm install --no-optional --no-audit
  - pip install -r requirements.txt
script:
  - make html-production
before_deploy:
  - pip install awscli
deploy:
  on:
    branch: master
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
after_deploy:
  # Bust the CloudFront edge cache, invalidate every object in the distribution
  - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
  - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_CDN_ID} --paths "/*"
